=== D-Mer/Easy-Life-Competition/图片/桌宠/二次元/兽耳&共存&帅哥&白毛/喵Pet/pet/animations/animation.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="thp/animation" elementFormDefault="qualified">
	<xs:element name="animations">
		<xs:complexType>
			<xs:attribute name="name" use="required"></xs:attribute>
			<xs:attribute name="version" type="xs:double" use="required"></xs:attribute>
			<xs:attribute name="type" type="xs:string" fixed="NORMAL"></xs:attribute>
			<xs:sequence>
				<xs:element name="animation" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="name" use="required"></xs:attribute>
						<xs:attribute name="loop" type="xs:int"></xs:attribute>
						<xs:sequence>
							<xs:element name="animationinfo">
								<xs:complexType>
									<xs:attribute name="path" type="xs:string" use="required"></xs:attribute>
									<xs:attribute name="delay" type="xs:int" use="required"></xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:sequence>
				<xs:element name="settings" maxOccurs="1">
					<xs:complexType>
						<xs:attribute name="width" use="required" type="xs:int"></xs:attribute>
						<xs:attribute name="height" use="required" type="xs:int"></xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== D-Mer/Easy-Life-Competition/图片/桌宠/二次元/兽耳&共存&帅哥&白毛/喵Pet/pet/animations/satori.xml
<?xml version="1.0" encoding="UTF-8"?>
<animations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:thp="http://www.thp.org/animation"
    name="satori"
    version="0.1"
    xmlns="thp"
    xsi:schemaLocation="thp/animation animation.xsd" >

    <settings
        height="128"
        width="128" >
    </settings>

    <animation
        name="stand"
        type="STAND|ACTIVE" >

        <animationinfo
            delay="5000"
            path="/satori/shime1.png" >
        </animationinfo>
    </animation>

    <animation
        name="walk"
        loop="10"
        type="WALK|ACTIVE" >

        <animationinfo
            delay="200"
            path="/satori/shime2.png" >
        </animationinfo>

        <animationinfo
            delay="200"
            path="/satori/shime3.png" >
        </animationinfo>
    </animation>

    <animation
        name="sleep"
        loop="20"
        type="SLEEP" >

        <animationinfo
            delay="1000"
            path="/satori/shime18.png" >
        </animationinfo>

        <animationinfo
            delay="1000"
            path="/satori/shime20.png" >
        </animationinfo>

        <animationinfo
            delay="1000"
            path="/satori/shime21.png" >
        </animationinfo>
    </animation>

    <animation
        name="sit"
        loop="20"
        type="SIT|ACTIVE" >

        <animationinfo
            delay="200"
            path="/satori/shime31.png" >
        </animationinfo>

        <animationinfo
            delay="200"
            path="/satori/shime32.png" >
        </animationinfo>

        <animationinfo
            delay="200"
            path="/satori/shime33.png" >
        </animationinfo>
    </animation>

    <animation
        name="sit2"
        type="SIT|ACTIVE" >

        <animationinfo
            delay="2000"
            path="/satori/shime26.png" >
        </animationinfo>

        <animationinfo
            delay="2000"
            path="/satori/shime27.png" >
        </animationinfo>

        <animationinfo
            delay="2000"
            path="/satori/shime26.png" >
        </animationinfo>

        <animationinfo
            delay="2000"
            path="/satori/shime27.png" >
        </animationinfo>

        <animationinfo
            delay="2000"
            path="/satori/shime28.png" >
        </animationinfo>

        <animationinfo
            delay="5000"
            path="/satori/shime29.png" >
        </animationinfo>
    </animation>

    <animation
        name="sit3"
        type="SIT|ACTIVE" >

        <animationinfo
            delay="5000"
            path="/satori/shime11.png" >
        </animationinfo>
    </animation>

</animations>
